FROM python:3.6.6-slim

# install dependencies
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
# RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app
COPY ./.coveragerc /usr/src/app/.coveragerc

# run server
CMD ["/usr/src/app/entrypoint.sh"]